package me.filthyweebdegenerate.pogadditions.init;

import me.filthyweebdegenerate.pogadditions.ItemGroups;
import me.filthyweebdegenerate.pogadditions.PogAdditions;
import net.minecraft.item.Food;
import net.minecraft.item.Item;
import net.minecraft.potion.EffectInstance;
import net.minecraft.potion.Effects;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public class FoodInit {
    public static final DeferredRegister<Item> FOOD_ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, PogAdditions.MOD_ID);

    public static final RegistryObject<Item> LongBread = FOOD_ITEMS.register("long_bread", () -> new Item(new Item.Properties().group(ItemGroups.pogAdditionsFood).food(new Food.Builder().effect(() -> new EffectInstance(Effects.ABSORPTION, 6000, 10), 1.0f).effect(() -> new EffectInstance(Effects.RESISTANCE, 6000, 5) , 1.0f).effect(() -> new EffectInstance(Effects.FIRE_RESISTANCE, 6000, 5), 1.0f).effect(() -> new EffectInstance(Effects.HASTE, 3600, 3), 1.0f).effect(() -> new EffectInstance(Effects.REGENERATION, 1200, 5), 1.0f).hunger(20).saturation(20.0f).setAlwaysEdible().fastToEat().build())));
    public static final RegistryObject<Item> EnchantedLongBread = FOOD_ITEMS.register("enchanted_long_bread", () -> new Item(new Item.Properties().group(ItemGroups.pogAdditionsFood).food(new Food.Builder().effect(() -> new EffectInstance(Effects.ABSORPTION, 12000, 15), 1.0f).effect(() -> new EffectInstance(Effects.FIRE_RESISTANCE, 12000, 15), 1.0f).effect(() -> new EffectInstance(Effects.RESISTANCE, 12000, 15), 1.0f).effect(() -> new EffectInstance(Effects.REGENERATION, 12000, 15), 1.0f).effect(() -> new EffectInstance(Effects.HASTE, 12000, 15), 1.0f).effect(() -> new EffectInstance(Effects.HEALTH_BOOST, 12000, 5), 1.0f).effect(() -> new EffectInstance(Effects.STRENGTH, 12000, 5), 1.0f).hunger(20).saturation(20.0f).setAlwaysEdible().fastToEat().build())));
    public static final RegistryObject<Item> EnchantedEnchantedLongBread = FOOD_ITEMS.register("enchanted_enchanted_long_bread", () -> new Item(new Item.Properties().group(ItemGroups.pogAdditionsFood).food(new Food.Builder().effect(() -> new EffectInstance(Effects.STRENGTH, 18000, 10), 1.0f).effect(() -> new EffectInstance(Effects.ABSORPTION, 18000, 20), 1.0f).effect(() -> new EffectInstance(Effects.HEALTH_BOOST, 18000, 20), 1.0f).effect(() -> new EffectInstance(Effects.FIRE_RESISTANCE, 18000, 20), 1.0f).effect(() -> new EffectInstance(Effects.RESISTANCE, 18000, 20), 1.0f).effect(() -> new EffectInstance(Effects.REGENERATION, 18000, 20), 1.0f).effect(() -> new EffectInstance(Effects.HASTE, 18000, 20), 1.0f).effect(() -> new EffectInstance(Effects.LUCK, 18000, 20), 1.0f).effect(() -> new EffectInstance(Effects.WATER_BREATHING, 18000, 40), 1.0f).effect(() -> new EffectInstance(Effects.DOLPHINS_GRACE, 18000, 1), 1.0f).effect(() -> new EffectInstance(Effects.NIGHT_VISION, 18000, 20), 1.0f).effect(() -> new EffectInstance(Effects.INSTANT_HEALTH, 18000, 40), 1.0f).hunger(20).saturation(20.0f).fastToEat().setAlwaysEdible().fastToEat().build())));
    public static final RegistryObject<Item> EDIBLE_SUPREME = FOOD_ITEMS.register("edible_supreme", () -> new Item(new Item.Properties().group(ItemGroups.pogAdditionsFood).food(new Food.Builder().effect(() -> new EffectInstance(Effects.ABSORPTION, 12000, 4), 1.0f).effect(() -> new EffectInstance(Effects.REGENERATION, 12000, 3) , 1.0f).setAlwaysEdible().saturation(10f).hunger(10).build())));
    public static final RegistryObject<Item> BIG_EDIBLE_SUPREME = FOOD_ITEMS.register("big_edible_supreme", () -> new Item(new Item.Properties().group(ItemGroups.pogAdditionsFood).food(new Food.Builder().effect(() -> new EffectInstance(Effects.ABSORPTION, 12000, 4), 1.0f).effect(() -> new EffectInstance(Effects.HEALTH_BOOST, 1200, 4), 1.0f).effect(() -> new EffectInstance(Effects.RESISTANCE, 12000, 2), 1.0f).effect(() -> new EffectInstance(Effects.FIRE_RESISTANCE, 12000, 2), 1.0f).setAlwaysEdible().fastToEat().saturation(20.0f).hunger(20).fastToEat().build())));
    public static final RegistryObject<Item> BIGGEST_EDIBLE_SUPREME = FOOD_ITEMS.register("biggest_edible_supreme", () -> new Item(new Item.Properties().group(ItemGroups.pogAdditionsFood).food(new Food.Builder().effect(() -> new EffectInstance(Effects.STRENGTH, 18000, 30), 1.0f).effect(() -> new EffectInstance(Effects.ABSORPTION, 18000, 25), 1.0f).effect(() -> new EffectInstance(Effects.HEALTH_BOOST, 18000, 25), 1.0f).effect(() -> new EffectInstance(Effects.FIRE_RESISTANCE, 18000, 25), 1.0f).effect(() -> new EffectInstance(Effects.RESISTANCE, 18000, 30), 1.0f).effect(() -> new EffectInstance(Effects.REGENERATION, 18000, 255), 1.0f).effect(() -> new EffectInstance(Effects.HASTE, 18000, 50), 1.0f).effect(() -> new EffectInstance(Effects.LUCK, 18000, 69), 1.0f).effect(() -> new EffectInstance(Effects.WATER_BREATHING, 18000, 255), 1.0f).effect(() -> new EffectInstance(Effects.DOLPHINS_GRACE, 18000, 3), 1.0f).effect(() -> new EffectInstance(Effects.NIGHT_VISION, 18000, 40), 1.0f).effect(() -> new EffectInstance(Effects.INSTANT_HEALTH, 18000, 255), 1.0f).effect(() -> new EffectInstance(Effects.SPEED, 18000, 3), 1.0f).effect(() -> new EffectInstance(Effects.JUMP_BOOST, 18000, 3), 1.0f).hunger(20).saturation(20.0f).fastToEat().setAlwaysEdible().fastToEat().build())));
}
